global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "node-exporter:9100"
  - job_name: "nginx-exporter"
    static_configs:
      - targets:
          - "nginx-exporter:9113"
  - job_name: "postgres-exporter"
    static_configs:
      - targets:
          - "postgres-exporter:9187"
